name: Workflows with large secrets
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  my-job:
    name: My Job
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          Password: ${{ secrets.Password }}
      - name: print home
        run: echo -e "\e[33m $HOME \e[0m"
      - name: Print pwd
        run: echo -e "\e[34m $PWD \e[0m"
      - name: setup try
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/secrets/my_secret.json"
          echo -e "\e[32m $GOOGLE_APPLICATION_CREDENTIALS \e[0m"
          exec whereis GOOGLE_APPLICATION_CREDENTIALS
      - name: setup try
        run: |
          export NAMES="ji sunta ho"
          echo -e "\e[32m $NAMES \e[0m"
      - name: Test printing your secret (Remove this step in production)
        run: echo -e "\e[32m Done \e[0m"
      - name: Print pwd
        run: echo -e "\e[34m $NAMES \e[0m"
      - uses: actions/setup-go@v4
        name: using golang now
        with:
          go-version: "1.21.1"
      - run: go version
      - uses: BerniWittmann/background-server-action@v1
        with:
          command: go version
          #          build: npm run build
          start: go run ./server && sleep 100 && kill -INT 888
          wait-on: "http://localhost:8000, http://localhost:8000/posts"
#      - name: start server
#        run: go run ./server.go && sleep 300 && kill -INT 888
#        wait-on: 'http://localhost:8080'
#      - name: stop server
#        run: kill -INT 888

