name: Workflows with large secrets
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          Password: ${{ secrets.Password }}
      - name: print home
        run: echo -e "\e[33m $HOME \e[0m"
      - name: Print pwd
        run: echo -e "\e[34m $PWD \e[0m"
      - name: setup try
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/secrets/my_secret.json"
          echo -e "\e[32m $GOOGLE_APPLICATION_CREDENTIALS \e[0m"
      - name: setup try
        run: |
          export NAMES="ji sunta ho"
          echo -e "\e[32m $NAME \e[0m"
      - name: Test printing your secret (Remove this step in production)
        run: echo -e "\e[32m Done \e[0m"
      - name: Print pwd
        run: echo -e "\e[34m $NAMES \e[0m"
